package com.unip.gui;

import com.unip.util.DAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Informacoes extends javax.swing.JFrame {

    /**
     * Creates new form Informacoes
     */
    public Informacoes() {
        initComponents();
    }

    public Informacoes(int nivel) {
        initComponents();
        
        Connection con = null;
        try {
            con = DAO.connectToDB();
            
            List<String[]> result = DAO.doQueryOperation(con, "SELECT * FROM Informacoes WHERE Nivel <= " + nivel);
            
            jTextArea1.setText("");
            jLabel2.setText("Você possui permissões de nível " + nivel);
            
            for (int i = 0; i < result.size(); i++) {
                jTextArea1.append("\nNível de informação: " + result.get(i)[0]);
                jTextArea1.append("\nInformação: " + result.get(i)[1] + "\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Informacoes.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (con != null) try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Informacoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informações");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setText("Olá Usuário!");
        jLabel1.setAutoscrolls(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Você possui permissões de nivel 1");
        jLabel2.setAutoscrolls(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setName("selectFile"); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n In eleifend orci a arcu vulputate viverra. Integer metus nisl,\n sagittis sed ultricies non, volutpat sit amet tellus.\n Aliquam vestibulum lorem sem. Donec eu odio quis lorem sagittis auctor.\n Nulla vel accumsan magna. Maecenas tempus enim ac enim maximus sodales\n. Aenean a viverra erat, et condimentum neque.\n Ut ut purus turpis.Lorem ipsum dolor sit amet,\n consectetur adipiscing elit.\nLorem ipsum dolor sit amet, consectetur adipiscing elit.\n In eleifend orci a arcu vulputate viverra. Integer metus nisl,\n sagittis sed ultricies non, volutpat sit amet tellus.\n Aliquam vestibulum lorem sem. Donec eu odio quis lorem sagittis auctor.\n Nulla vel accumsan magna. Maecenas tempus enim ac enim maximus sodales\n. Aenean a viverra erat, et condimentum neque.\n Ut ut purus turpis.Lorem ipsum dolor sit amet,\n consectetur adipiscing elit.\nLorem ipsum dolor sit amet, consectetur adipiscing elit.\n In eleifend orci a arcu vulputate viverra. Integer metus nisl,\n sagittis sed ultricies non, volutpat sit amet tellus.\n Aliquam vestibulum lorem sem. Donec eu odio quis lorem sagittis auctor.\n Nulla vel accumsan magna. Maecenas tempus enim ac enim maximus sodales\n. Aenean a viverra erat, et condimentum neque.\n Ut ut purus turpis.Lorem ipsum dolor sit amet,\n consectetur adipiscing elit.\nLorem ipsum dolor sit amet, consectetur adipiscing elit.\n In eleifend orci a arcu vulputate viverra. Integer metus nisl,\n sagittis sed ultricies non, volutpat sit amet tellus.\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
